In [1]:
pip install tensorflow

     |████████████████████████████████| 421.8 MB 29 kB/s  eta 0:00:019  |▍                               | 5.3 MB 1.5 MB/s eta 0:04:42     |█                               | 12.0 MB 415 kB/s eta 0:16:27     |██▋                             | 34.2 MB 3.2 MB/s eta 0:02:03     |████▌                           | 58.8 MB 170 kB/s eta 0:35:23     |████▊                           | 62.6 MB 877 kB/s eta 0:06:50     |█████                           | 67.2 MB 1.6 MB/s eta 0:03:43     |█████▍                          | 71.6 MB 1.0 MB/s eta 0:05:39     |██████▉                         | 89.5 MB 1.0 MB/s eta 0:05:27     |███████▎                        | 96.4 MB 2.2 MB/s eta 0:02:29     |████████                        | 104.9 MB 2.7 MB/s eta 0:01:57     |████████▏                       | 108.1 MB 1.9 MB/s eta 0:02:48     |████████▋                       | 113.2 MB 857 kB/s eta 0:06:00     |█████████▍                      | 123.6 MB 1.7 MB/s eta 0:03:01     |█████████▋                      | 127.1 

In [6]:
import tensorflow as tf

In [7]:
tf.__version__

'2.1.0'

# 1- Session

In [11]:
#Last version :(
sess =  tf.Session()
b = tf.constant(5)
print(sess.run(b))

AttributeError: module 'tensorflow' has no attribute 'Session'

In [10]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

hello = tf.constant('Hello, TensorFlow!')

sess = tf.compat.v1.Session()

print(sess.run(hello))

b'Hello, TensorFlow!'


In [13]:
c = tf.constant(8)
with  tf.compat.v1.Session() as sess : 
    print(sess.run(c))

8


# 2- Constant

In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

In [2]:
a = tf.constant(3)
b = tf.constant(3,tf.float32)
c = tf.constant([2,5,6,9,6])
d = tf.constant([[2,5,6],
                 [8,5,8],
                 [8,8,1]])
e = tf.constant('I love TensorFlow')

In [6]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
with  tf.compat.v1.Session() as sess :
    print('a = ',sess.run(a))
    print('b = ',sess.run(b))
    print('c = ',sess.run(c))
    print('d = \n',sess.run(d))
    print('e = ',sess.run(e))

a =  3
b =  3.0
c =  [2 5 6 9 6]
d = 
 [[2 5 6]
 [8 5 8]
 [8 8 1]]
e =  b'I love TensorFlow'


In [17]:
b

<tf.Tensor 'Const_4:0' shape=() dtype=float32>

# 3- Variable

In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

In [2]:
a = tf.Variable(3)
b = tf.Variable(3,tf.float32)
c = tf.Variable([2,5,6,9,6])
d = tf.Variable([[2,5,6],[8,5,8], [8,8,1]])
e = tf.Variable('I love TensorFlow')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [3]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32>

In [4]:
with  tf.compat.v1.Session() as sess :
    sess.run(tf.compat.v1.global_variables_initializer())
    print('a = ',sess.run(a))
    print('b = ',sess.run(b))
    print('c = ',sess.run(c))
    print('d = \n',sess.run(d))
    print('e = ',sess.run(e))

a =  3
b =  3
c =  [2 5 6 9 6]
d = 
 [[2 5 6]
 [8 5 8]
 [8 8 1]]
e =  b'I love TensorFlow'


In [6]:
price = tf.Variable(20) 
sess = tf.compat.v1.Session()
init = tf.compat.v1.global_variables_initializer()
sess.run(init)
print('original price is : ',sess.run(price))

original price is :  20


In [9]:
price = tf.Variable(30) 
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(40) 
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(50) 
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(60) 
sess.run(tf.compat.v1.global_variables_initializer())
print('the price is : ',sess.run(price))

the price is :  30
the price is :  40
the price is :  50
the price is :  60


In [11]:
'''
value = tf.assign(value,newvalue)
'''
price = tf.compat.v1.assign(price,50)
print('new price is : ',sess.run(price))

new price is :  50


In [15]:
for j in range(10) : 
    price = tf.compat.v1.assign(price,price+10)
    print('new price is : ',sess.run(price))

new price is :  120
new price is :  130
new price is :  140
new price is :  150
new price is :  160
new price is :  170
new price is :  180
new price is :  190
new price is :  200
new price is :  210


# 4-Placeholder

In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

In [5]:
a = tf.compat.v1.placeholder(tf.float32)
with tf.compat.v1.Session() as sess : 
    result = sess.run(a , feed_dict ={a:3})
    print(result)

3.0


In [6]:
a = tf.compat.v1.placeholder(tf.float32)
b = a*2
with tf.compat.v1.Session() as sess : 
    result = sess.run(b , feed_dict ={a:3})
    print(result)

6.0


In [5]:
x = tf.compat.v1.placeholder(tf.float32)
y = tf.compat.v1.placeholder(tf.float32)
z = tf.compat.v1.placeholder(tf.float32)
w = tf.compat.v1.placeholder(tf.float32)

b = x*2 + 3*y**4 - 4/z + w-9

with tf.compat.v1.Session() as sess : 
    result = sess.run(b , feed_dict ={x:3,y:4,z:8,w:6})
    print(result)

770.5


In [7]:
x = tf.compat.v1.placeholder(tf.float32)
y = x**2
with tf.compat.v1.Session() as sess :
    print(sess.run(y,feed_dict={x:5}))

25.0


In [8]:
x = tf.compat.v1.placeholder(tf.float32)
y = x**2
with tf.compat.v1.Session() as sess :
    print(sess.run(y, {x:[5,8,10,50]}))

[  25.   64.  100. 2500.]


In [9]:
x = tf.compat.v1.placeholder(tf.float32)
y = x**2
with tf.compat.v1.Session() as sess :
        print(sess.run(y, {x:list(range(5,100))}))

[  25.   36.   49.   64.   81.  100.  121.  144.  169.  196.  225.  256.
  289.  324.  361.  400.  441.  484.  529.  576.  625.  676.  729.  784.
  841.  900.  961. 1024. 1089. 1156. 1225. 1296. 1369. 1444. 1521. 1600.
 1681. 1764. 1849. 1936. 2025. 2116. 2209. 2304. 2401. 2500. 2601. 2704.
 2809. 2916. 3025. 3136. 3249. 3364. 3481. 3600. 3721. 3844. 3969. 4096.
 4225. 4356. 4489. 4624. 4761. 4900. 5041. 5184. 5329. 5476. 5625. 5776.
 5929. 6084. 6241. 6400. 6561. 6724. 6889. 7056. 7225. 7396. 7569. 7744.
 7921. 8100. 8281. 8464. 8649. 8836. 9025. 9216. 9409. 9604. 9801.]


In [10]:
w = tf.compat.v1.constant([5.0])
b = tf.compat.v1.Variable([7.0],tf.float32)

x = tf.compat.v1.placeholder(tf.float32)

LinearRegressionModel = w*x + b

with tf.compat.v1.Session() as sess :
    sess.run(tf.compat.v1.global_variables_initializer())
    print(sess.run(LinearRegressionModel,{x:[3,5,7,9]}))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[22. 32. 42. 52.]


# 5- Operations

In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

In [2]:
s1 = tf.constant('hi ')
s2 = tf.constant('people ')
s3 = tf.add(s1,s2)

sess = tf.compat.v1.Session()
print(sess.run(s3))

b'hi people '


In [3]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.add(s1,s2)
sess = tf.compat.v1.Session()
print(sess.run(s3))

50


In [4]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.multiply(s1,s2)

sess = tf.compat.v1.Session()
print(sess.run(s3))

600


In [5]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.subtract(s1,s2)

sess = tf.compat.v1.Session()
print(sess.run(s3))

-10


In [6]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.divide(s1,s2)
sess = tf.compat.v1.Session()
print(sess.run(s3))

0.6666666666666666


In [8]:
s1 = tf.constant(20)
s2 = tf.constant(3)
s3 = tf.pow(s1,s2)
sess = tf.compat.v1.Session()
print(sess.run(s3))

8000


In [10]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant(30)
s3 = tf.add(s1,s2)
sess = tf.compat.v1.Session()
print(sess.run(s3))

[ 6  8 10 12]


In [11]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4])
s3 = tf.add(s1,s2)
sess = tf.compat.v1.Session()
print(sess.run(s3))

[ 6  8 10 12]


In [12]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4,8,9,7,8,9])
s3 = tf.add(s1,s2)
sess = tf.compat.v1.Session()
print(sess.run(s3))

ValueError: Dimensions must be equal, but are 4 and 9 for 'Add_5' (op: 'Add') with input shapes: [4], [9].

In [13]:
matrix1 = tf.constant([[5., 3.]])
matrix2 = tf.constant([[2.],
                       [2.]])
product = tf.matmul(matrix1, matrix2)


with tf.compat.v1.Session() as sess:
    result = sess.run(product)
    print (result)

[[16.]]


In [15]:
matrix1 = tf.constant([[5,6,9,8],
                      [1,2,8,9],
                      [7,9,5,6],
                      [1,2,3,9]])
matrix2 = tf.compat.v1.matrix_transpose(matrix1)

with tf.compat.v1.Session() as sess:
    result = sess.run(matrix2)
    print (result)

[[5 1 7 1]
 [6 2 9 2]
 [9 8 5 3]
 [8 9 6 9]]


# 6- Graph

In [1]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
#sess = tf.compat.v1.Session()
graph = tf.compat.v1.get_default_graph()
graph.get_operations()

[]

In [2]:
a= tf.constant(5)
graph.get_operations()

[<tf.Operation 'Const' type=Const>]

In [4]:
b= tf.constant(7)
graph.get_operations()

[<tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>]

In [5]:
c= tf.add(a,b)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>]

In [7]:
d= tf.compat.v1.placeholder(tf.float32)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>]

In [8]:
e= tf.compat.v1.Variable(2)
graph.get_operations()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'Variable/Initializer/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VarHandleOp>,
 <tf.Operation 'Variable/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'Variable/Assign' type=AssignVariableOp>,
 <tf.Operation 'Variable/Read/ReadVariableOp' type=ReadVariableOp>]

In [9]:
for operation in graph.get_operations() :
    print(operation.name)

Const
Const_1
Add
Placeholder
Variable/Initializer/initial_value
Variable
Variable/IsInitialized/VarIsInitializedOp
Variable/Assign
Variable/Read/ReadVariableOp


# 7- Eager Execution

In [2]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

In [4]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.compat.v1.encode_base64("hello world"))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [5]:
x = tf.matmul([[1]], [[2, 3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [6]:
# Define constant tensors
print("Define constant tensors")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

Define constant tensors
a = 2
b = 3


In [7]:
# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")
c = a + b
print("a + b = %i" % c)
d = a * b
print("a * b = %i" % d)

# Full compatibility with Numpy
print("Mixing operations with Tensors and Numpy Arrays")

Running operations, without tf.Session
a + b = 5
a * b = 6
Mixing operations with Tensors and Numpy Arrays


In [8]:
import numpy as np
# Define constant tensors
a = tf.constant([[2., 1.],
                 [1., 0.]], dtype=tf.float32)
print("Tensor:\n a = %s" % a)
b = np.array([[3., 0.],
              [5., 1.]], dtype=np.float32)
print("NumpyArray:\n b = %s" % b)

# Run the operation without the need for tf.Session
print("Running operations, without tf.Session")

Tensor:
 a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
 b = [[3. 0.]
 [5. 1.]]
Running operations, without tf.Session


In [9]:
c = a + b
print("a + b = %s" % c)

d = tf.matmul(a, b)
print("a * b = %s" % d)

print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

a + b = tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)
Iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
